// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: remotedb/proto/defs.proto

package protodb

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Operation_Type int32

const (
	Operation_SET    Operation_Type = 0
	Operation_DELETE Operation_Type = 1
)

var Operation_Type_name = map[int32]string{
	0: "SET",
	1: "DELETE",
}

var Operation_Type_value = map[string]int32{
	"SET":    0,
	"DELETE": 1,
}

func (x Operation_Type) String() string {
	return proto.EnumName(Operation_Type_name, int32(x))
}

func (Operation_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef1eada6618d0075, []int{1, 0}
}

type Batch struct {
	Ops                  []*Operation `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Batch) Reset()         { *m = Batch{} }
func (m *Batch) String() string { return proto.CompactTextString(m) }
func (*Batch) ProtoMessage()    {}
func (*Batch) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1eada6618d0075, []int{0}
}
func (m *Batch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Batch.Unmarshal(m, b)
}
func (m *Batch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Batch.Marshal(b, m, deterministic)
}
func (m *Batch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Batch.Merge(m, src)
}
func (m *Batch) XXX_Size() int {
	return xxx_messageInfo_Batch.Size(m)
}
func (m *Batch) XXX_DiscardUnknown() {
	xxx_messageInfo_Batch.DiscardUnknown(m)
}

var xxx_messageInfo_Batch proto.InternalMessageInfo

func (m *Batch) GetOps() []*Operation {
	if m != nil {
		return m.Ops
	}
	return nil
}

type Operation struct {
	Entity               *Entity        `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Type                 Operation_Type `protobuf:"varint,2,opt,name=type,proto3,enum=protodb.Operation_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1eada6618d0075, []int{1}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *Operation) GetType() Operation_Type {
	if m != nil {
		return m.Type
	}
	return Operation_SET
}

type Entity struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Exists               bool     `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`
	Start                []byte   `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	End                  []byte   `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	Err                  string   `protobuf:"bytes,7,opt,name=err,proto3" json:"err,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1eada6618d0075, []int{2}
}
func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Entity) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Entity) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *Entity) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Entity) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Entity) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *Entity) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1eada6618d0075, []int{3}
}
func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type Iterator struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Iterator) Reset()         { *m = Iterator{} }
func (m *Iterator) String() string { return proto.CompactTextString(m) }
func (*Iterator) ProtoMessage()    {}
func (*Iterator) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1eada6618d0075, []int{4}
}
func (m *Iterator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Iterator.Unmarshal(m, b)
}
func (m *Iterator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Iterator.Marshal(b, m, deterministic)
}
func (m *Iterator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Iterator.Merge(m, src)
}
func (m *Iterator) XXX_Size() int {
	return xxx_messageInfo_Iterator.Size(m)
}
func (m *Iterator) XXX_DiscardUnknown() {
	xxx_messageInfo_Iterator.DiscardUnknown(m)
}

var xxx_messageInfo_Iterator proto.InternalMessageInfo

func (m *Iterator) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Iterator) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Iterator) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Stats struct {
	Data                 map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TimeAt               int64             `protobuf:"varint,2,opt,name=time_at,json=timeAt,proto3" json:"time_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1eada6618d0075, []int{5}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Stats) GetTimeAt() int64 {
	if m != nil {
		return m.TimeAt
	}
	return 0
}

type Init struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Dir                  string   `protobuf:"bytes,3,opt,name=Dir,proto3" json:"Dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Init) Reset()         { *m = Init{} }
func (m *Init) String() string { return proto.CompactTextString(m) }
func (*Init) ProtoMessage()    {}
func (*Init) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef1eada6618d0075, []int{6}
}
func (m *Init) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Init.Unmarshal(m, b)
}
func (m *Init) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Init.Marshal(b, m, deterministic)
}
func (m *Init) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Init.Merge(m, src)
}
func (m *Init) XXX_Size() int {
	return xxx_messageInfo_Init.Size(m)
}
func (m *Init) XXX_DiscardUnknown() {
	xxx_messageInfo_Init.DiscardUnknown(m)
}

var xxx_messageInfo_Init proto.InternalMessageInfo

func (m *Init) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Init) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Init) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func init() {
	proto.RegisterEnum("protodb.Operation_Type", Operation_Type_name, Operation_Type_value)
	proto.RegisterType((*Batch)(nil), "protodb.Batch")
	proto.RegisterType((*Operation)(nil), "protodb.Operation")
	proto.RegisterType((*Entity)(nil), "protodb.Entity")
	proto.RegisterType((*Nothing)(nil), "protodb.Nothing")
	proto.RegisterType((*Iterator)(nil), "protodb.Iterator")
	proto.RegisterType((*Stats)(nil), "protodb.Stats")
	proto.RegisterMapType((map[string]string)(nil), "protodb.Stats.DataEntry")
	proto.RegisterType((*Init)(nil), "protodb.Init")
}

func init() { proto.RegisterFile("remotedb/proto/defs.proto", fileDescriptor_ef1eada6618d0075) }

var fileDescriptor_ef1eada6618d0075 = []byte{
	// 629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xce, 0xda, 0x8e, 0x13, 0x4f, 0xfb, 0xa6, 0x79, 0x57, 0xaf, 0xde, 0x9a, 0x20, 0xaa, 0xc8,
	0x42, 0xc2, 0x50, 0xea, 0x96, 0x14, 0x89, 0x8f, 0x13, 0xad, 0x12, 0x89, 0x4a, 0xa8, 0x48, 0x4e,
	0x25, 0x8e, 0x68, 0x13, 0x4f, 0x13, 0x8b, 0xc6, 0x8e, 0xd6, 0xd3, 0x8a, 0x5c, 0xb8, 0xf2, 0x57,
	0xb8, 0x72, 0xe3, 0xef, 0xd0, 0x5f, 0x81, 0xc4, 0x05, 0xed, 0xae, 0x93, 0xaa, 0x1f, 0x07, 0x73,
	0xca, 0x3c, 0x33, 0xcf, 0xf3, 0xec, 0x8c, 0x67, 0xb3, 0x70, 0x4f, 0xe2, 0x2c, 0x27, 0x4c, 0x46,
	0xbb, 0x73, 0x99, 0x53, 0xbe, 0x9b, 0xe0, 0x69, 0x11, 0xe9, 0x90, 0x37, 0xf4, 0x4f, 0x32, 0xea,
	0xec, 0x4c, 0x52, 0x9a, 0x9e, 0x8f, 0xa2, 0x71, 0x3e, 0xdb, 0x9d, 0xe4, 0x93, 0xdc, 0x50, 0x47,
	0xe7, 0xa7, 0x1a, 0x19, 0x9d, 0x8a, 0x8c, 0x2e, 0xd8, 0x81, 0xfa, 0xa1, 0xa0, 0xf1, 0x94, 0x3f,
	0x04, 0x3b, 0x9f, 0x17, 0x3e, 0xeb, 0xda, 0xe1, 0x5a, 0x8f, 0x47, 0xa5, 0x5d, 0xf4, 0x7e, 0x8e,
	0x52, 0x50, 0x9a, 0x67, 0xb1, 0x2a, 0x07, 0x5f, 0xc0, 0x5b, 0x65, 0xf8, 0x23, 0x70, 0x31, 0xa3,
	0x94, 0x16, 0x3e, 0xeb, 0xb2, 0x70, 0xad, 0xb7, 0xb1, 0x52, 0x0d, 0x74, 0x3a, 0x2e, 0xcb, 0x7c,
	0x1b, 0x1c, 0x5a, 0xcc, 0xd1, 0xb7, 0xba, 0x2c, 0x6c, 0xf5, 0x36, 0x6f, 0x9b, 0x47, 0x27, 0x8b,
	0x39, 0xc6, 0x9a, 0x14, 0xdc, 0x07, 0x47, 0x21, 0xde, 0x00, 0x7b, 0x38, 0x38, 0x69, 0xd7, 0x38,
	0x80, 0xdb, 0x1f, 0xbc, 0x1b, 0x9c, 0x0c, 0xda, 0x2c, 0xf8, 0xce, 0xc0, 0x35, 0xe6, 0xbc, 0x05,
	0x56, 0x9a, 0xe8, 0x93, 0xeb, 0xb1, 0x95, 0x26, 0xbc, 0x0d, 0xf6, 0x27, 0x5c, 0xe8, 0x33, 0xd6,
	0x63, 0x15, 0xf2, 0xff, 0xa0, 0x7e, 0x21, 0xce, 0xce, 0xd1, 0xb7, 0x75, 0xce, 0x00, 0xfe, 0x3f,
	0xb8, 0xf8, 0x39, 0x2d, 0xa8, 0xf0, 0x9d, 0x2e, 0x0b, 0x9b, 0x71, 0x89, 0x14, 0xbb, 0x20, 0x21,
	0xc9, 0xaf, 0x1b, 0xb6, 0x06, 0xca, 0x15, 0xb3, 0xc4, 0x77, 0x8d, 0x2b, 0x66, 0xfa, 0x1c, 0x94,
	0xd2, 0x6f, 0x74, 0x59, 0xe8, 0xc5, 0x2a, 0xe4, 0x0f, 0x00, 0xc6, 0x12, 0x05, 0x61, 0xf2, 0x51,
	0x90, 0xdf, 0xec, 0xb2, 0xd0, 0x8e, 0xbd, 0x32, 0x73, 0x40, 0x81, 0x07, 0x8d, 0xe3, 0x9c, 0xa6,
	0x69, 0x36, 0x09, 0xde, 0x42, 0xf3, 0x88, 0xd4, 0xcc, 0xb9, 0x2c, 0xbb, 0x2b, 0x47, 0x68, 0xc6,
	0x06, 0x54, 0x9d, 0x22, 0xf8, 0xca, 0xa0, 0x3e, 0x24, 0x41, 0x05, 0x7f, 0x0a, 0x4e, 0x22, 0x48,
	0x94, 0x9b, 0xf3, 0x57, 0x1f, 0x57, 0x57, 0xa3, 0xbe, 0x20, 0x31, 0xc8, 0x48, 0x2e, 0x62, 0xcd,
	0xe2, 0x9b, 0xd0, 0xa0, 0x74, 0x86, 0xaa, 0x51, 0x4b, 0x37, 0xea, 0x2a, 0x78, 0x40, 0x9d, 0x17,
	0xe0, 0xad, 0xb8, 0xcb, 0x2e, 0x98, 0x99, 0xf1, 0x5a, 0x17, 0x96, 0xce, 0x19, 0xf0, 0xda, 0x7a,
	0xc9, 0x82, 0x37, 0xe0, 0x1c, 0x65, 0x29, 0x71, 0x6e, 0xf6, 0x56, 0x8a, 0xcc, 0x0e, 0x39, 0x38,
	0xc7, 0x62, 0xb6, 0x14, 0xe9, 0x58, 0x79, 0xf7, 0x53, 0xa9, 0xa7, 0xf1, 0x62, 0x15, 0xf6, 0x7e,
	0x3b, 0x60, 0xf5, 0x0f, 0x79, 0x08, 0x4e, 0xaa, 0x8c, 0xfe, 0x59, 0x8d, 0xa0, 0x7c, 0x3b, 0x37,
	0x6f, 0x55, 0x50, 0xe3, 0x8f, 0xc1, 0x9e, 0x20, 0xf1, 0x9b, 0x95, 0xbb, 0xa8, 0xfb, 0xe0, 0x4d,
	0x90, 0x86, 0x24, 0x51, 0xcc, 0xaa, 0x08, 0x42, 0xb6, 0xc7, 0x94, 0xff, 0x54, 0x14, 0x95, 0xfc,
	0x9f, 0x80, 0x5d, 0xdc, 0xd5, 0x4a, 0x7b, 0x95, 0x58, 0xee, 0xbe, 0xc6, 0x23, 0x68, 0x14, 0x48,
	0xc3, 0x45, 0x36, 0xae, 0xc6, 0xdf, 0x01, 0x37, 0xc1, 0x33, 0x24, 0xac, 0x46, 0x7f, 0x06, 0x60,
	0xe8, 0xd5, 0x4f, 0xe8, 0x41, 0x33, 0x5d, 0xde, 0xc7, 0x5b, 0x82, 0x7f, 0xaf, 0xf6, 0x50, 0x72,
	0x82, 0xda, 0x1e, 0xe3, 0xaf, 0x60, 0x43, 0xe2, 0x05, 0xca, 0x02, 0x8f, 0xfe, 0x56, 0xba, 0xad,
	0xff, 0x62, 0x54, 0xf0, 0x5b, 0xbd, 0x74, 0x5a, 0xd7, 0xef, 0x6d, 0x50, 0xe3, 0x7b, 0x00, 0x23,
	0xf5, 0x32, 0x7d, 0x90, 0x29, 0x21, 0xbf, 0xaa, 0xeb, 0xe7, 0xea, 0xce, 0x69, 0x9e, 0x43, 0xeb,
	0x4a, 0xa1, 0x3f, 0x42, 0x05, 0xd5, 0xe1, 0xfa, 0xaf, 0x9f, 0x5b, 0xec, 0xdb, 0xe5, 0x16, 0xfb,
	0x71, 0xb9, 0xc5, 0x46, 0xae, 0x26, 0xec, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xdb, 0xe3,
	0x23, 0x6b, 0x05, 0x00, 0x00,
}

func (this *Batch) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Batch)
	if !ok {
		that2, ok := that.(Batch)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Ops) != len(that1.Ops) {
		return false
	}
	for i := range this.Ops {
		if !this.Ops[i].Equal(that1.Ops[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Operation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Operation)
	if !ok {
		that2, ok := that.(Operation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Entity.Equal(that1.Entity) {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Entity) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Entity)
	if !ok {
		that2, ok := that.(Entity)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return false
	}
	if !bytes.Equal(this.Value, that1.Value) {
		return false
	}
	if this.Exists != that1.Exists {
		return false
	}
	if !bytes.Equal(this.Start, that1.Start) {
		return false
	}
	if !bytes.Equal(this.End, that1.End) {
		return false
	}
	if this.Err != that1.Err {
		return false
	}
	if this.CreatedAt != that1.CreatedAt {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Nothing) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Nothing)
	if !ok {
		that2, ok := that.(Nothing)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Iterator) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Iterator)
	if !ok {
		that2, ok := that.(Iterator)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Valid != that1.Valid {
		return false
	}
	if !bytes.Equal(this.Key, that1.Key) {
		return false
	}
	if !bytes.Equal(this.Value, that1.Value) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Stats) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Stats)
	if !ok {
		that2, ok := that.(Stats)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Data) != len(that1.Data) {
		return false
	}
	for i := range this.Data {
		if this.Data[i] != that1.Data[i] {
			return false
		}
	}
	if this.TimeAt != that1.TimeAt {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Init) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Init)
	if !ok {
		that2, ok := that.(Init)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Dir != that1.Dir {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DBClient is the client API for DB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DBClient interface {
	Init(ctx context.Context, in *Init, opts ...grpc.CallOption) (*Entity, error)
	Get(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Entity, error)
	GetStream(ctx context.Context, opts ...grpc.CallOption) (DB_GetStreamClient, error)
	Has(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Entity, error)
	Set(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Nothing, error)
	SetSync(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Nothing, error)
	Delete(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Nothing, error)
	DeleteSync(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Nothing, error)
	Iterator(ctx context.Context, in *Entity, opts ...grpc.CallOption) (DB_IteratorClient, error)
	ReverseIterator(ctx context.Context, in *Entity, opts ...grpc.CallOption) (DB_ReverseIteratorClient, error)
	// rpc print(Nothing) returns (Entity) {}
	Stats(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Stats, error)
	BatchWrite(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*Nothing, error)
	BatchWriteSync(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*Nothing, error)
}

type dBClient struct {
	cc *grpc.ClientConn
}

func NewDBClient(cc *grpc.ClientConn) DBClient {
	return &dBClient{cc}
}

func (c *dBClient) Init(ctx context.Context, in *Init, opts ...grpc.CallOption) (*Entity, error) {
	out := new(Entity)
	err := c.cc.Invoke(ctx, "/protodb.DB/init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Get(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Entity, error) {
	out := new(Entity)
	err := c.cc.Invoke(ctx, "/protodb.DB/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) GetStream(ctx context.Context, opts ...grpc.CallOption) (DB_GetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DB_serviceDesc.Streams[0], "/protodb.DB/getStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBGetStreamClient{stream}
	return x, nil
}

type DB_GetStreamClient interface {
	Send(*Entity) error
	Recv() (*Entity, error)
	grpc.ClientStream
}

type dBGetStreamClient struct {
	grpc.ClientStream
}

func (x *dBGetStreamClient) Send(m *Entity) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dBGetStreamClient) Recv() (*Entity, error) {
	m := new(Entity)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBClient) Has(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Entity, error) {
	out := new(Entity)
	err := c.cc.Invoke(ctx, "/protodb.DB/has", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Set(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/protodb.DB/set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) SetSync(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/protodb.DB/setSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Delete(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/protodb.DB/delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) DeleteSync(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/protodb.DB/deleteSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Iterator(ctx context.Context, in *Entity, opts ...grpc.CallOption) (DB_IteratorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DB_serviceDesc.Streams[1], "/protodb.DB/iterator", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBIteratorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DB_IteratorClient interface {
	Recv() (*Iterator, error)
	grpc.ClientStream
}

type dBIteratorClient struct {
	grpc.ClientStream
}

func (x *dBIteratorClient) Recv() (*Iterator, error) {
	m := new(Iterator)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBClient) ReverseIterator(ctx context.Context, in *Entity, opts ...grpc.CallOption) (DB_ReverseIteratorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DB_serviceDesc.Streams[2], "/protodb.DB/reverseIterator", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBReverseIteratorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DB_ReverseIteratorClient interface {
	Recv() (*Iterator, error)
	grpc.ClientStream
}

type dBReverseIteratorClient struct {
	grpc.ClientStream
}

func (x *dBReverseIteratorClient) Recv() (*Iterator, error) {
	m := new(Iterator)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBClient) Stats(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/protodb.DB/stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) BatchWrite(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/protodb.DB/batchWrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) BatchWriteSync(ctx context.Context, in *Batch, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/protodb.DB/batchWriteSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBServer is the server API for DB service.
type DBServer interface {
	Init(context.Context, *Init) (*Entity, error)
	Get(context.Context, *Entity) (*Entity, error)
	GetStream(DB_GetStreamServer) error
	Has(context.Context, *Entity) (*Entity, error)
	Set(context.Context, *Entity) (*Nothing, error)
	SetSync(context.Context, *Entity) (*Nothing, error)
	Delete(context.Context, *Entity) (*Nothing, error)
	DeleteSync(context.Context, *Entity) (*Nothing, error)
	Iterator(*Entity, DB_IteratorServer) error
	ReverseIterator(*Entity, DB_ReverseIteratorServer) error
	// rpc print(Nothing) returns (Entity) {}
	Stats(context.Context, *Nothing) (*Stats, error)
	BatchWrite(context.Context, *Batch) (*Nothing, error)
	BatchWriteSync(context.Context, *Batch) (*Nothing, error)
}

// UnimplementedDBServer can be embedded to have forward compatible implementations.
type UnimplementedDBServer struct {
}

func (*UnimplementedDBServer) Init(ctx context.Context, req *Init) (*Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedDBServer) Get(ctx context.Context, req *Entity) (*Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedDBServer) GetStream(srv DB_GetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (*UnimplementedDBServer) Has(ctx context.Context, req *Entity) (*Entity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Has not implemented")
}
func (*UnimplementedDBServer) Set(ctx context.Context, req *Entity) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedDBServer) SetSync(ctx context.Context, req *Entity) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSync not implemented")
}
func (*UnimplementedDBServer) Delete(ctx context.Context, req *Entity) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedDBServer) DeleteSync(ctx context.Context, req *Entity) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSync not implemented")
}
func (*UnimplementedDBServer) Iterator(req *Entity, srv DB_IteratorServer) error {
	return status.Errorf(codes.Unimplemented, "method Iterator not implemented")
}
func (*UnimplementedDBServer) ReverseIterator(req *Entity, srv DB_ReverseIteratorServer) error {
	return status.Errorf(codes.Unimplemented, "method ReverseIterator not implemented")
}
func (*UnimplementedDBServer) Stats(ctx context.Context, req *Nothing) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (*UnimplementedDBServer) BatchWrite(ctx context.Context, req *Batch) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchWrite not implemented")
}
func (*UnimplementedDBServer) BatchWriteSync(ctx context.Context, req *Batch) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchWriteSync not implemented")
}

func RegisterDBServer(s *grpc.Server, srv DBServer) {
	s.RegisterService(&_DB_serviceDesc, srv)
}

func _DB_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Init)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Init(ctx, req.(*Init))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Get(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DBServer).GetStream(&dBGetStreamServer{stream})
}

type DB_GetStreamServer interface {
	Send(*Entity) error
	Recv() (*Entity, error)
	grpc.ServerStream
}

type dBGetStreamServer struct {
	grpc.ServerStream
}

func (x *dBGetStreamServer) Send(m *Entity) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dBGetStreamServer) Recv() (*Entity, error) {
	m := new(Entity)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DB_Has_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Has(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/Has",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Has(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Set(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_SetSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).SetSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/SetSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).SetSync(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Delete(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_DeleteSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).DeleteSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/DeleteSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).DeleteSync(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Iterator_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Entity)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DBServer).Iterator(m, &dBIteratorServer{stream})
}

type DB_IteratorServer interface {
	Send(*Iterator) error
	grpc.ServerStream
}

type dBIteratorServer struct {
	grpc.ServerStream
}

func (x *dBIteratorServer) Send(m *Iterator) error {
	return x.ServerStream.SendMsg(m)
}

func _DB_ReverseIterator_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Entity)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DBServer).ReverseIterator(m, &dBReverseIteratorServer{stream})
}

type DB_ReverseIteratorServer interface {
	Send(*Iterator) error
	grpc.ServerStream
}

type dBReverseIteratorServer struct {
	grpc.ServerStream
}

func (x *dBReverseIteratorServer) Send(m *Iterator) error {
	return x.ServerStream.SendMsg(m)
}

func _DB_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Stats(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_BatchWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Batch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).BatchWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/BatchWrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).BatchWrite(ctx, req.(*Batch))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_BatchWriteSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Batch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).BatchWriteSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodb.DB/BatchWriteSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).BatchWriteSync(ctx, req.(*Batch))
	}
	return interceptor(ctx, in, info, handler)
}

var _DB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protodb.DB",
	HandlerType: (*DBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "init",
			Handler:    _DB_Init_Handler,
		},
		{
			MethodName: "get",
			Handler:    _DB_Get_Handler,
		},
		{
			MethodName: "has",
			Handler:    _DB_Has_Handler,
		},
		{
			MethodName: "set",
			Handler:    _DB_Set_Handler,
		},
		{
			MethodName: "setSync",
			Handler:    _DB_SetSync_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _DB_Delete_Handler,
		},
		{
			MethodName: "deleteSync",
			Handler:    _DB_DeleteSync_Handler,
		},
		{
			MethodName: "stats",
			Handler:    _DB_Stats_Handler,
		},
		{
			MethodName: "batchWrite",
			Handler:    _DB_BatchWrite_Handler,
		},
		{
			MethodName: "batchWriteSync",
			Handler:    _DB_BatchWriteSync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getStream",
			Handler:       _DB_GetStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "iterator",
			Handler:       _DB_Iterator_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "reverseIterator",
			Handler:       _DB_ReverseIterator_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "remotedb/proto/defs.proto",
}

func NewPopulatedBatch(r randyDefs, easy bool) *Batch {
	this := &Batch{}
	if r.Intn(5) != 0 {
		v1 := r.Intn(5)
		this.Ops = make([]*Operation, v1)
		for i := 0; i < v1; i++ {
			this.Ops[i] = NewPopulatedOperation(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedDefs(r, 2)
	}
	return this
}

func NewPopulatedOperation(r randyDefs, easy bool) *Operation {
	this := &Operation{}
	if r.Intn(5) != 0 {
		this.Entity = NewPopulatedEntity(r, easy)
	}
	this.Type = Operation_Type([]int32{0, 1}[r.Intn(2)])
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedDefs(r, 3)
	}
	return this
}

func NewPopulatedEntity(r randyDefs, easy bool) *Entity {
	this := &Entity{}
	this.Id = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Id *= -1
	}
	v2 := r.Intn(100)
	this.Key = make([]byte, v2)
	for i := 0; i < v2; i++ {
		this.Key[i] = byte(r.Intn(256))
	}
	v3 := r.Intn(100)
	this.Value = make([]byte, v3)
	for i := 0; i < v3; i++ {
		this.Value[i] = byte(r.Intn(256))
	}
	this.Exists = bool(bool(r.Intn(2) == 0))
	v4 := r.Intn(100)
	this.Start = make([]byte, v4)
	for i := 0; i < v4; i++ {
		this.Start[i] = byte(r.Intn(256))
	}
	v5 := r.Intn(100)
	this.End = make([]byte, v5)
	for i := 0; i < v5; i++ {
		this.End[i] = byte(r.Intn(256))
	}
	this.Err = string(randStringDefs(r))
	this.CreatedAt = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.CreatedAt *= -1
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedDefs(r, 9)
	}
	return this
}

func NewPopulatedNothing(r randyDefs, easy bool) *Nothing {
	this := &Nothing{}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedDefs(r, 1)
	}
	return this
}

func NewPopulatedIterator(r randyDefs, easy bool) *Iterator {
	this := &Iterator{}
	this.Valid = bool(bool(r.Intn(2) == 0))
	v6 := r.Intn(100)
	this.Key = make([]byte, v6)
	for i := 0; i < v6; i++ {
		this.Key[i] = byte(r.Intn(256))
	}
	v7 := r.Intn(100)
	this.Value = make([]byte, v7)
	for i := 0; i < v7; i++ {
		this.Value[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedDefs(r, 4)
	}
	return this
}

func NewPopulatedStats(r randyDefs, easy bool) *Stats {
	this := &Stats{}
	if r.Intn(5) != 0 {
		v8 := r.Intn(10)
		this.Data = make(map[string]string)
		for i := 0; i < v8; i++ {
			this.Data[randStringDefs(r)] = randStringDefs(r)
		}
	}
	this.TimeAt = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.TimeAt *= -1
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedDefs(r, 3)
	}
	return this
}

func NewPopulatedInit(r randyDefs, easy bool) *Init {
	this := &Init{}
	this.Type = string(randStringDefs(r))
	this.Name = string(randStringDefs(r))
	this.Dir = string(randStringDefs(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedDefs(r, 4)
	}
	return this
}

type randyDefs interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneDefs(r randyDefs) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringDefs(r randyDefs) string {
	v9 := r.Intn(100)
	tmps := make([]rune, v9)
	for i := 0; i < v9; i++ {
		tmps[i] = randUTF8RuneDefs(r)
	}
	return string(tmps)
}
func randUnrecognizedDefs(r randyDefs, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldDefs(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldDefs(dAtA []byte, r randyDefs, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateDefs(dAtA, uint64(key))
		v10 := r.Int63()
		if r.Intn(2) == 0 {
			v10 *= -1
		}
		dAtA = encodeVarintPopulateDefs(dAtA, uint64(v10))
	case 1:
		dAtA = encodeVarintPopulateDefs(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateDefs(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateDefs(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateDefs(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateDefs(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
