name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  cleanup-runs:
    runs-on: self-hosted
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  Test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: test & coverage report creation
        uses: ./
        with:
          cmd: |
            go test ./... -mod=readonly -timeout 8m -race -coverprofile=coverage.txt -covermode=atomic -tags=memdb,goleveldb,cleveldb,boltdb,rocksdb,badgerdb -v
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true  
