name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  Test:
    # The custom image here contains pre-built libraries for leveldb and
    # rocksdb, which are needed to build and test those modules.
    # To update the container image, see docker.yml.
    runs-on: ubuntu-latest
    container:
      image: line/tm-db-testing
      env:
        CGO_LDFLAGS: -lrocksdb
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: test & coverage report creation
        run: |
          go test ./... -mod=readonly -timeout 8m -race -coverprofile=coverage.txt -covermode=atomic \
          -tags=cleveldb,rocksdb,boltdb,badgerdb -v
      - uses: codecov/codecov-action@v2.0.3
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
