name: Lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    # We need to run the linter on the same image we use for building, since it
    # needs the C libraries installed for the dependencies to typecheck.
    runs-on: ubuntu-latest
    container:
      image: line/tm-db-testing
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v3.1.0
        with:
          # Required: the version of golangci-lint is required and must be
          # specified without patch version: we always use the latest patch
          # version.
          version: v1.42.1
          args: --timeout 10m --build-tags "cleveldb,boltdb,badgerdb" # ignore rocksdb
          github-token: ${{ secrets.github_token }}
