name: Lint with registered Docker Image
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      CACHE_DIR:
        required: false
        type: string
      CACHE_FILE:
        required: false
        type: string
      TAG:
        required: false
        type: string

jobs:
  changes:
    runs-on: ubuntu-latest
    if: ${{ inputs.CACHE_FILE == '' }}
    outputs:
      paths: ${{ steps.filter.outputs.paths }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            paths:
              - "contrib/*"
              - "tools/*"
              - "go.mod"

  lint-with-registerd-docker-image:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ inputs.CACHE_FILE == '' && needs.changes.outputs.paths != 'true' }}
    container:
      image: line/tm-db-testing
      env:
        CGO_LDFLAGS: -lrocksdb
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - uses: actions/checkout@v3
      - name: lint
        run: |
          golangci-lint run -v --timeout 5m --build-tags 'cleveldb,rocksdb,boltdb,badgerdb'

  lint:
    runs-on: ubuntu-latest
    if: ${{ inputs.CACHE_FILE != '' }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker Image
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ inputs.CACHE_DIR }}
          key: ${{ inputs.CACHE_FILE }}

      - name: Load Docker Image
        run: |
          docker load -i ${{ inputs.CACHE_FILE }}

      - name: lint
        run: |
          docker run -e CGO_LDFLAGS=-lrocksdb --rm -v "$(pwd)":/workspace -w /workspace ${{ inputs.TAG }} bash -c "\
          golangci-lint run -v --timeout 5m --build-tags 'cleveldb,rocksdb,boltdb,badgerdb' \
          "
